from environs import Env

env = Env()
# Read .env into os.environ
env.read_env()


# KAFKA SETTINGS
CLIENT_ID = env.str("CLIENT_ID")
BOOTSTRAP_SERVERS = env.list("BOOTSTRAP_SERVERS")
KAFKA_ADDRESS_RESOLVE_TOPIC=env.str("KAFKA_ADDRESS_RESOLVE_TOPIC")
KAFKA_PROCESSED_TOPIC=env.str("KAFKA_PROCESSED_TOPIC")
KAFKA_INTENT_TOPIC=env.str("KAFKA_INTENT_TOPIC")
INTENT_TARGET_TOPIC=env.str("INTENT_TARGET_TOPIC")
HF_HUB_TOKEN = env.str("HF_HUB_TOKEN")
# GROUP_ID=env.int("GROUP_ID", None)

# Max message pool count
MAX_POOL_RECORDS=env.int("MAX_POOL_RECORDS")
MESSAGE_TIMEOUT_MS=env.int("MESSAGE_TIMEOUT_MS")
SECURITY_PROTOCOL=env.str("SECURITY_PROTOCOL")
SASL_MECHANISMS=env.str("SASL_MECHANISMS")
SASL_PLAIN_USERNAME=env.str("SASL_PLAIN_USERNAME")
SASL_PLAIN_PASSWORD=env.str("SASL_PLAIN_PASSWORD")
ENABLE_AUTO_COMMIT=env.bool("ENABLE_AUTO_COMMIT")

# Third party api key
SENTRY_DSN = env.str("SENTRY_DSN")
GOOGLE_API_KEY = env.str("GOOGLE_API_KEY")
OPENAI_API_KEY = env.str("OPENAI_API_KEY")
NER_API_KEY = env.str("NER_API_KEY")
